# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from doublecloud.clickhouse.v1 import backup_pb2 as doublecloud_dot_clickhouse_dot_v1_dot_backup__pb2
from doublecloud.clickhouse.v1 import backup_service_pb2 as doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2
from doublecloud.v1 import operation_pb2 as doublecloud_dot_v1_dot_operation__pb2


class BackupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/doublecloud.clickhouse.v1.BackupService/Get',
                request_serializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.GetBackupRequest.SerializeToString,
                response_deserializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__pb2.Backup.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/doublecloud.clickhouse.v1.BackupService/List',
                request_serializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.ListBackupsRequest.SerializeToString,
                response_deserializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.ListBackupsResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/doublecloud.clickhouse.v1.BackupService/Create',
                request_serializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.CreateBackupRequest.SerializeToString,
                response_deserializer=doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/doublecloud.clickhouse.v1.BackupService/Delete',
                request_serializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.DeleteBackupRequest.SerializeToString,
                response_deserializer=doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)


class BackupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Returns the specified backup of ClickHouse cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Returns the list of available backups for the specified ClickHouse cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Creates new ClickHouse cluster backup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete specified ClickHouse cluster backup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.GetBackupRequest.FromString,
                    response_serializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__pb2.Backup.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.ListBackupsRequest.FromString,
                    response_serializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.ListBackupsResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.CreateBackupRequest.FromString,
                    response_serializer=doublecloud_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.DeleteBackupRequest.FromString,
                    response_serializer=doublecloud_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doublecloud.clickhouse.v1.BackupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('doublecloud.clickhouse.v1.BackupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BackupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.clickhouse.v1.BackupService/Get',
            doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.GetBackupRequest.SerializeToString,
            doublecloud_dot_clickhouse_dot_v1_dot_backup__pb2.Backup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.clickhouse.v1.BackupService/List',
            doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.ListBackupsRequest.SerializeToString,
            doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.ListBackupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.clickhouse.v1.BackupService/Create',
            doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.CreateBackupRequest.SerializeToString,
            doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.clickhouse.v1.BackupService/Delete',
            doublecloud_dot_clickhouse_dot_v1_dot_backup__service__pb2.DeleteBackupRequest.SerializeToString,
            doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
