# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doublecloud/transfer/v1/endpoint/metrica.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'doublecloud/transfer/v1/endpoint/metrica.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from doublecloud.transfer.v1.endpoint import common_pb2 as doublecloud_dot_transfer_dot_v1_dot_endpoint_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.doublecloud/transfer/v1/endpoint/metrica.proto\x12 doublecloud.transfer.v1.endpoint\x1a-doublecloud/transfer/v1/endpoint/common.proto\"X\n\rMetricaStream\x12G\n\x04type\x18\x01 \x01(\x0e\x32\x33.doublecloud.transfer.v1.endpoint.MetricaStreamTypeR\x04type\"\xe6\x01\n\rMetricaSource\x12\x1f\n\x0b\x63ounter_ids\x18\x01 \x03(\x03R\ncounterIds\x12>\n\x05token\x18\x02 \x01(\x0b\x32(.doublecloud.transfer.v1.endpoint.SecretR\x05token\x12I\n\x07streams\x18\x03 \x03(\x0b\x32/.doublecloud.transfer.v1.endpoint.MetricaStreamR\x07streams\x12)\n\x10\x65nable_dashboard\x18\x04 \x01(\x08R\x0f\x65nableDashboard*y\n\x11MetricaStreamType\x12#\n\x1fMETRICA_STREAM_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n\x1aMETRICA_STREAM_TYPE_VISITS\x10\x01\x12\x1f\n\x1bMETRICA_STREAM_TYPE_HITS_V2\x10\x02\x42NZLgithub.com/doublecloud/go-genproto/doublecloud/transfer/v1/endpoint;endpointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doublecloud.transfer.v1.endpoint.metrica_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZLgithub.com/doublecloud/go-genproto/doublecloud/transfer/v1/endpoint;endpoint'
  _globals['_METRICASTREAMTYPE']._serialized_start=454
  _globals['_METRICASTREAMTYPE']._serialized_end=575
  _globals['_METRICASTREAM']._serialized_start=131
  _globals['_METRICASTREAM']._serialized_end=219
  _globals['_METRICASOURCE']._serialized_start=222
  _globals['_METRICASOURCE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
