# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doublecloud/logs/v1/log.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'doublecloud/logs/v1/log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from doublecloud.logs.v1 import log_source_pb2 as doublecloud_dot_logs_dot_v1_dot_log__source__pb2
from doublecloud.v1 import paging_pb2 as doublecloud_dot_v1_dot_paging__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x64oublecloud/logs/v1/log.proto\x12\x13\x64oublecloud.logs.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$doublecloud/logs/v1/log_source.proto\x1a\x1b\x64oublecloud/v1/paging.proto\"\xf2\x02\n\x08\x43riteria\x12\x38\n\x07sources\x18\x01 \x03(\x0b\x32\x1e.doublecloud.logs.v1.LogSourceR\x07sources\x12\x37\n\tfrom_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x08\x66romTime\x12\x33\n\x07to_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x06toTime\x12\x35\n\x06levels\x18\x04 \x03(\x0e\x32\x1d.doublecloud.logs.v1.LogLevelR\x06levels\x12\x16\n\x06\x66ilter\x18\x05 \x01(\tR\x06\x66ilter\x12=\n\nsort_order\x18\x06 \x01(\x0e\x32\x1e.doublecloud.logs.v1.SortOrderR\tsortOrder\x12\x30\n\x06paging\x18\x07 \x01(\x0b\x32\x18.doublecloud.v1.NextPageR\x06paging\"\xeb\x01\n\tLogRecord\x12\x36\n\x06source\x18\x01 \x01(\x0b\x32\x1e.doublecloud.logs.v1.LogSourceR\x06source\x12\x1a\n\x08instance\x18\x02 \x01(\tR\x08instance\x12;\n\x0brecord_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\nrecordTime\x12\x33\n\x05level\x18\x04 \x01(\x0e\x32\x1d.doublecloud.logs.v1.LogLevelR\x05level\x12\x18\n\x07message\x18\x05 \x01(\tR\x07message*X\n\tSortOrder\x12\x16\n\x12SORT_ORDER_INVALID\x10\x00\x12\x18\n\x14SORT_ORDER_ASCENDING\x10\x01\x12\x19\n\x15SORT_ORDER_DESCENDING\x10\x02*\x88\x01\n\x08LogLevel\x12\x15\n\x11LOG_LEVEL_DEFAULT\x10\x00\x12\x13\n\x0fLOG_LEVEL_DEBUG\x10\x02\x12\x12\n\x0eLOG_LEVEL_INFO\x10\x03\x12\x12\n\x0eLOG_LEVEL_WARN\x10\x04\x12\x13\n\x0fLOG_LEVEL_ERROR\x10\x05\x12\x13\n\x0fLOG_LEVEL_FATAL\x10\x06\x42=Z;github.com/doublecloud/go-genproto/doublecloud/logs/v1;logsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doublecloud.logs.v1.log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/doublecloud/go-genproto/doublecloud/logs/v1;logs'
  _globals['_SORTORDER']._serialized_start=765
  _globals['_SORTORDER']._serialized_end=853
  _globals['_LOGLEVEL']._serialized_start=856
  _globals['_LOGLEVEL']._serialized_end=992
  _globals['_CRITERIA']._serialized_start=155
  _globals['_CRITERIA']._serialized_end=525
  _globals['_LOGRECORD']._serialized_start=528
  _globals['_LOGRECORD']._serialized_end=763
# @@protoc_insertion_point(module_scope)
