from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class FacebookMarketingSource(_message.Message):
    __slots__ = ("start_date", "end_date", "account_id", "access_token", "include_deleted", "fetch_thumbnail_images", "custom_insights")
    class Field(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        FIELD_UNSPECIFIED: _ClassVar[FacebookMarketingSource.Field]
        ACCOUNT_CURRENCY: _ClassVar[FacebookMarketingSource.Field]
        ACCOUNT_ID: _ClassVar[FacebookMarketingSource.Field]
        ACCOUNT_NAME: _ClassVar[FacebookMarketingSource.Field]
        ACTION_VALUES: _ClassVar[FacebookMarketingSource.Field]
        ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        AD_BID_VALUE: _ClassVar[FacebookMarketingSource.Field]
        AD_CLICK_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        AD_ID: _ClassVar[FacebookMarketingSource.Field]
        AD_IMPRESSION_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        AD_NAME: _ClassVar[FacebookMarketingSource.Field]
        ADSET_BID_VALUE: _ClassVar[FacebookMarketingSource.Field]
        ADSET_END: _ClassVar[FacebookMarketingSource.Field]
        ADSET_ID: _ClassVar[FacebookMarketingSource.Field]
        ADSET_NAME: _ClassVar[FacebookMarketingSource.Field]
        ADSET_START: _ClassVar[FacebookMarketingSource.Field]
        AGE_TARGETING: _ClassVar[FacebookMarketingSource.Field]
        ATTRIBUTION_SETTING: _ClassVar[FacebookMarketingSource.Field]
        AUCTION_BID: _ClassVar[FacebookMarketingSource.Field]
        AUCTION_COMPETITIVENESS: _ClassVar[FacebookMarketingSource.Field]
        AUCTION_MAX_COMPETITOR_BID: _ClassVar[FacebookMarketingSource.Field]
        BUYING_TYPE: _ClassVar[FacebookMarketingSource.Field]
        CAMPAIGN_ID: _ClassVar[FacebookMarketingSource.Field]
        CAMPAIGN_NAME: _ClassVar[FacebookMarketingSource.Field]
        CANVAS_AVG_VIEW_PERCENT: _ClassVar[FacebookMarketingSource.Field]
        CANVAS_AVG_VIEW_TIME: _ClassVar[FacebookMarketingSource.Field]
        CATALOG_SEGMENT_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        CATALOG_SEGMENT_VALUE: _ClassVar[FacebookMarketingSource.Field]
        CATALOG_SEGMENT_VALUE_MOBILE_PURCHASE_ROAS: _ClassVar[FacebookMarketingSource.Field]
        CATALOG_SEGMENT_VALUE_OMNI_PURCHASE_ROAS: _ClassVar[FacebookMarketingSource.Field]
        CATALOG_SEGMENT_VALUE_WEBSITE_PURCHASE_ROAS: _ClassVar[FacebookMarketingSource.Field]
        CLICKS: _ClassVar[FacebookMarketingSource.Field]
        CONVERSION_RATE_RANKING: _ClassVar[FacebookMarketingSource.Field]
        CONVERSION_VALUES: _ClassVar[FacebookMarketingSource.Field]
        CONVERSIONS: _ClassVar[FacebookMarketingSource.Field]
        CONVERTED_PRODUCT_QUANTITY: _ClassVar[FacebookMarketingSource.Field]
        CONVERTED_PRODUCT_VALUE: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_15_SEC_VIDEO_VIEW: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_2_SEC_CONTINUOUS_VIDEO_VIEW: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_ACTION_TYPE: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_AD_CLICK: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_CONVERSION: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_DDA_COUNTBY_CONVS: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_ESTIMATED_AD_RECALLERS: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_INLINE_LINK_CLICK: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_INLINE_POST_ENGAGEMENT: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_ONE_THOUSAND_AD_IMPRESSION: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_OUTBOUND_CLICK: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_THRUPLAY: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_UNIQUE_ACTION_TYPE: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_UNIQUE_CLICK: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_UNIQUE_CONVERSION: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_UNIQUE_INLINE_LINK_CLICK: _ClassVar[FacebookMarketingSource.Field]
        COST_PER_UNIQUE_OUTBOUND_CLICK: _ClassVar[FacebookMarketingSource.Field]
        CPC: _ClassVar[FacebookMarketingSource.Field]
        CPM: _ClassVar[FacebookMarketingSource.Field]
        CPP: _ClassVar[FacebookMarketingSource.Field]
        CREATED_TIME: _ClassVar[FacebookMarketingSource.Field]
        CTR: _ClassVar[FacebookMarketingSource.Field]
        DATE_START: _ClassVar[FacebookMarketingSource.Field]
        DATE_STOP: _ClassVar[FacebookMarketingSource.Field]
        DDA_COUNTBY_CONVS: _ClassVar[FacebookMarketingSource.Field]
        DDA_RESULTS: _ClassVar[FacebookMarketingSource.Field]
        ENGAGEMENT_RATE_RANKING: _ClassVar[FacebookMarketingSource.Field]
        ESTIMATED_AD_RECALL_RATE: _ClassVar[FacebookMarketingSource.Field]
        ESTIMATED_AD_RECALL_RATE_LOWER_BOUND: _ClassVar[FacebookMarketingSource.Field]
        ESTIMATED_AD_RECALL_RATE_UPPER_BOUND: _ClassVar[FacebookMarketingSource.Field]
        ESTIMATED_AD_RECALLERS: _ClassVar[FacebookMarketingSource.Field]
        ESTIMATED_AD_RECALLERS_LOWER_BOUND: _ClassVar[FacebookMarketingSource.Field]
        ESTIMATED_AD_RECALLERS_UPPER_BOUND: _ClassVar[FacebookMarketingSource.Field]
        FREQUENCY: _ClassVar[FacebookMarketingSource.Field]
        FULL_VIEW_IMPRESSIONS: _ClassVar[FacebookMarketingSource.Field]
        FULL_VIEW_REACH: _ClassVar[FacebookMarketingSource.Field]
        GENDER_TARGETING: _ClassVar[FacebookMarketingSource.Field]
        IMPRESSIONS: _ClassVar[FacebookMarketingSource.Field]
        INLINE_LINK_CLICK_CTR: _ClassVar[FacebookMarketingSource.Field]
        INLINE_LINK_CLICKS: _ClassVar[FacebookMarketingSource.Field]
        INLINE_POST_ENGAGEMENT: _ClassVar[FacebookMarketingSource.Field]
        INSTANT_EXPERIENCE_CLICKS_TO_OPEN: _ClassVar[FacebookMarketingSource.Field]
        INSTANT_EXPERIENCE_CLICKS_TO_START: _ClassVar[FacebookMarketingSource.Field]
        INSTANT_EXPERIENCE_OUTBOUND_CLICKS: _ClassVar[FacebookMarketingSource.Field]
        INTERACTIVE_COMPONENT_TAP: _ClassVar[FacebookMarketingSource.Field]
        LABELS: _ClassVar[FacebookMarketingSource.Field]
        LOCATION: _ClassVar[FacebookMarketingSource.Field]
        MOBILE_APP_PURCHASE_ROAS: _ClassVar[FacebookMarketingSource.Field]
        OBJECTIVE: _ClassVar[FacebookMarketingSource.Field]
        OPTIMIZATION_GOAL: _ClassVar[FacebookMarketingSource.Field]
        OUTBOUND_CLICKS: _ClassVar[FacebookMarketingSource.Field]
        OUTBOUND_CLICKS_CTR: _ClassVar[FacebookMarketingSource.Field]
        PLACE_PAGE_NAME: _ClassVar[FacebookMarketingSource.Field]
        PURCHASE_ROAS: _ClassVar[FacebookMarketingSource.Field]
        QUALIFYING_QUESTION_QUALIFY_ANSWER_RATE: _ClassVar[FacebookMarketingSource.Field]
        QUALITY_RANKING: _ClassVar[FacebookMarketingSource.Field]
        QUALITY_SCORE_ECTR: _ClassVar[FacebookMarketingSource.Field]
        QUALITY_SCORE_ECVR: _ClassVar[FacebookMarketingSource.Field]
        QUALITY_SCORE_ORGANIC: _ClassVar[FacebookMarketingSource.Field]
        REACH: _ClassVar[FacebookMarketingSource.Field]
        SOCIAL_SPEND: _ClassVar[FacebookMarketingSource.Field]
        SPEND: _ClassVar[FacebookMarketingSource.Field]
        TOTAL_POSTBACKS: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_CLICKS: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_CONVERSIONS: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_CTR: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_INLINE_LINK_CLICK_CTR: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_INLINE_LINK_CLICKS: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_LINK_CLICKS_CTR: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_OUTBOUND_CLICKS: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_OUTBOUND_CLICKS_CTR: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_VIDEO_CONTINUOUS_2_SEC_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        UNIQUE_VIDEO_VIEW_15_SEC: _ClassVar[FacebookMarketingSource.Field]
        UPDATED_TIME: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_15_SEC_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_30_SEC_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_AVG_TIME_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_CONTINUOUS_2_SEC_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_P100_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_P25_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_P50_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_P75_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_P95_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_PLAY_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_PLAY_CURVE_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_PLAY_RETENTION_0_TO_15S_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_PLAY_RETENTION_20_TO_60S_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_PLAY_RETENTION_GRAPH_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_THRUPLAY_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        VIDEO_TIME_WATCHED_ACTIONS: _ClassVar[FacebookMarketingSource.Field]
        WEBSITE_CTR: _ClassVar[FacebookMarketingSource.Field]
        WEBSITE_PURCHASE_ROAS: _ClassVar[FacebookMarketingSource.Field]
        WISH_BID: _ClassVar[FacebookMarketingSource.Field]
    FIELD_UNSPECIFIED: FacebookMarketingSource.Field
    ACCOUNT_CURRENCY: FacebookMarketingSource.Field
    ACCOUNT_ID: FacebookMarketingSource.Field
    ACCOUNT_NAME: FacebookMarketingSource.Field
    ACTION_VALUES: FacebookMarketingSource.Field
    ACTIONS: FacebookMarketingSource.Field
    AD_BID_VALUE: FacebookMarketingSource.Field
    AD_CLICK_ACTIONS: FacebookMarketingSource.Field
    AD_ID: FacebookMarketingSource.Field
    AD_IMPRESSION_ACTIONS: FacebookMarketingSource.Field
    AD_NAME: FacebookMarketingSource.Field
    ADSET_BID_VALUE: FacebookMarketingSource.Field
    ADSET_END: FacebookMarketingSource.Field
    ADSET_ID: FacebookMarketingSource.Field
    ADSET_NAME: FacebookMarketingSource.Field
    ADSET_START: FacebookMarketingSource.Field
    AGE_TARGETING: FacebookMarketingSource.Field
    ATTRIBUTION_SETTING: FacebookMarketingSource.Field
    AUCTION_BID: FacebookMarketingSource.Field
    AUCTION_COMPETITIVENESS: FacebookMarketingSource.Field
    AUCTION_MAX_COMPETITOR_BID: FacebookMarketingSource.Field
    BUYING_TYPE: FacebookMarketingSource.Field
    CAMPAIGN_ID: FacebookMarketingSource.Field
    CAMPAIGN_NAME: FacebookMarketingSource.Field
    CANVAS_AVG_VIEW_PERCENT: FacebookMarketingSource.Field
    CANVAS_AVG_VIEW_TIME: FacebookMarketingSource.Field
    CATALOG_SEGMENT_ACTIONS: FacebookMarketingSource.Field
    CATALOG_SEGMENT_VALUE: FacebookMarketingSource.Field
    CATALOG_SEGMENT_VALUE_MOBILE_PURCHASE_ROAS: FacebookMarketingSource.Field
    CATALOG_SEGMENT_VALUE_OMNI_PURCHASE_ROAS: FacebookMarketingSource.Field
    CATALOG_SEGMENT_VALUE_WEBSITE_PURCHASE_ROAS: FacebookMarketingSource.Field
    CLICKS: FacebookMarketingSource.Field
    CONVERSION_RATE_RANKING: FacebookMarketingSource.Field
    CONVERSION_VALUES: FacebookMarketingSource.Field
    CONVERSIONS: FacebookMarketingSource.Field
    CONVERTED_PRODUCT_QUANTITY: FacebookMarketingSource.Field
    CONVERTED_PRODUCT_VALUE: FacebookMarketingSource.Field
    COST_PER_15_SEC_VIDEO_VIEW: FacebookMarketingSource.Field
    COST_PER_2_SEC_CONTINUOUS_VIDEO_VIEW: FacebookMarketingSource.Field
    COST_PER_ACTION_TYPE: FacebookMarketingSource.Field
    COST_PER_AD_CLICK: FacebookMarketingSource.Field
    COST_PER_CONVERSION: FacebookMarketingSource.Field
    COST_PER_DDA_COUNTBY_CONVS: FacebookMarketingSource.Field
    COST_PER_ESTIMATED_AD_RECALLERS: FacebookMarketingSource.Field
    COST_PER_INLINE_LINK_CLICK: FacebookMarketingSource.Field
    COST_PER_INLINE_POST_ENGAGEMENT: FacebookMarketingSource.Field
    COST_PER_ONE_THOUSAND_AD_IMPRESSION: FacebookMarketingSource.Field
    COST_PER_OUTBOUND_CLICK: FacebookMarketingSource.Field
    COST_PER_THRUPLAY: FacebookMarketingSource.Field
    COST_PER_UNIQUE_ACTION_TYPE: FacebookMarketingSource.Field
    COST_PER_UNIQUE_CLICK: FacebookMarketingSource.Field
    COST_PER_UNIQUE_CONVERSION: FacebookMarketingSource.Field
    COST_PER_UNIQUE_INLINE_LINK_CLICK: FacebookMarketingSource.Field
    COST_PER_UNIQUE_OUTBOUND_CLICK: FacebookMarketingSource.Field
    CPC: FacebookMarketingSource.Field
    CPM: FacebookMarketingSource.Field
    CPP: FacebookMarketingSource.Field
    CREATED_TIME: FacebookMarketingSource.Field
    CTR: FacebookMarketingSource.Field
    DATE_START: FacebookMarketingSource.Field
    DATE_STOP: FacebookMarketingSource.Field
    DDA_COUNTBY_CONVS: FacebookMarketingSource.Field
    DDA_RESULTS: FacebookMarketingSource.Field
    ENGAGEMENT_RATE_RANKING: FacebookMarketingSource.Field
    ESTIMATED_AD_RECALL_RATE: FacebookMarketingSource.Field
    ESTIMATED_AD_RECALL_RATE_LOWER_BOUND: FacebookMarketingSource.Field
    ESTIMATED_AD_RECALL_RATE_UPPER_BOUND: FacebookMarketingSource.Field
    ESTIMATED_AD_RECALLERS: FacebookMarketingSource.Field
    ESTIMATED_AD_RECALLERS_LOWER_BOUND: FacebookMarketingSource.Field
    ESTIMATED_AD_RECALLERS_UPPER_BOUND: FacebookMarketingSource.Field
    FREQUENCY: FacebookMarketingSource.Field
    FULL_VIEW_IMPRESSIONS: FacebookMarketingSource.Field
    FULL_VIEW_REACH: FacebookMarketingSource.Field
    GENDER_TARGETING: FacebookMarketingSource.Field
    IMPRESSIONS: FacebookMarketingSource.Field
    INLINE_LINK_CLICK_CTR: FacebookMarketingSource.Field
    INLINE_LINK_CLICKS: FacebookMarketingSource.Field
    INLINE_POST_ENGAGEMENT: FacebookMarketingSource.Field
    INSTANT_EXPERIENCE_CLICKS_TO_OPEN: FacebookMarketingSource.Field
    INSTANT_EXPERIENCE_CLICKS_TO_START: FacebookMarketingSource.Field
    INSTANT_EXPERIENCE_OUTBOUND_CLICKS: FacebookMarketingSource.Field
    INTERACTIVE_COMPONENT_TAP: FacebookMarketingSource.Field
    LABELS: FacebookMarketingSource.Field
    LOCATION: FacebookMarketingSource.Field
    MOBILE_APP_PURCHASE_ROAS: FacebookMarketingSource.Field
    OBJECTIVE: FacebookMarketingSource.Field
    OPTIMIZATION_GOAL: FacebookMarketingSource.Field
    OUTBOUND_CLICKS: FacebookMarketingSource.Field
    OUTBOUND_CLICKS_CTR: FacebookMarketingSource.Field
    PLACE_PAGE_NAME: FacebookMarketingSource.Field
    PURCHASE_ROAS: FacebookMarketingSource.Field
    QUALIFYING_QUESTION_QUALIFY_ANSWER_RATE: FacebookMarketingSource.Field
    QUALITY_RANKING: FacebookMarketingSource.Field
    QUALITY_SCORE_ECTR: FacebookMarketingSource.Field
    QUALITY_SCORE_ECVR: FacebookMarketingSource.Field
    QUALITY_SCORE_ORGANIC: FacebookMarketingSource.Field
    REACH: FacebookMarketingSource.Field
    SOCIAL_SPEND: FacebookMarketingSource.Field
    SPEND: FacebookMarketingSource.Field
    TOTAL_POSTBACKS: FacebookMarketingSource.Field
    UNIQUE_ACTIONS: FacebookMarketingSource.Field
    UNIQUE_CLICKS: FacebookMarketingSource.Field
    UNIQUE_CONVERSIONS: FacebookMarketingSource.Field
    UNIQUE_CTR: FacebookMarketingSource.Field
    UNIQUE_INLINE_LINK_CLICK_CTR: FacebookMarketingSource.Field
    UNIQUE_INLINE_LINK_CLICKS: FacebookMarketingSource.Field
    UNIQUE_LINK_CLICKS_CTR: FacebookMarketingSource.Field
    UNIQUE_OUTBOUND_CLICKS: FacebookMarketingSource.Field
    UNIQUE_OUTBOUND_CLICKS_CTR: FacebookMarketingSource.Field
    UNIQUE_VIDEO_CONTINUOUS_2_SEC_WATCHED_ACTIONS: FacebookMarketingSource.Field
    UNIQUE_VIDEO_VIEW_15_SEC: FacebookMarketingSource.Field
    UPDATED_TIME: FacebookMarketingSource.Field
    VIDEO_15_SEC_WATCHED_ACTIONS: FacebookMarketingSource.Field
    VIDEO_30_SEC_WATCHED_ACTIONS: FacebookMarketingSource.Field
    VIDEO_AVG_TIME_WATCHED_ACTIONS: FacebookMarketingSource.Field
    VIDEO_CONTINUOUS_2_SEC_WATCHED_ACTIONS: FacebookMarketingSource.Field
    VIDEO_P100_WATCHED_ACTIONS: FacebookMarketingSource.Field
    VIDEO_P25_WATCHED_ACTIONS: FacebookMarketingSource.Field
    VIDEO_P50_WATCHED_ACTIONS: FacebookMarketingSource.Field
    VIDEO_P75_WATCHED_ACTIONS: FacebookMarketingSource.Field
    VIDEO_P95_WATCHED_ACTIONS: FacebookMarketingSource.Field
    VIDEO_PLAY_ACTIONS: FacebookMarketingSource.Field
    VIDEO_PLAY_CURVE_ACTIONS: FacebookMarketingSource.Field
    VIDEO_PLAY_RETENTION_0_TO_15S_ACTIONS: FacebookMarketingSource.Field
    VIDEO_PLAY_RETENTION_20_TO_60S_ACTIONS: FacebookMarketingSource.Field
    VIDEO_PLAY_RETENTION_GRAPH_ACTIONS: FacebookMarketingSource.Field
    VIDEO_THRUPLAY_WATCHED_ACTIONS: FacebookMarketingSource.Field
    VIDEO_TIME_WATCHED_ACTIONS: FacebookMarketingSource.Field
    WEBSITE_CTR: FacebookMarketingSource.Field
    WEBSITE_PURCHASE_ROAS: FacebookMarketingSource.Field
    WISH_BID: FacebookMarketingSource.Field
    class Breakdown(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        BREAKDOWN_UNSPECIFIED: _ClassVar[FacebookMarketingSource.Breakdown]
        AD_FORMAT_ASSET: _ClassVar[FacebookMarketingSource.Breakdown]
        AGE: _ClassVar[FacebookMarketingSource.Breakdown]
        APP_ID: _ClassVar[FacebookMarketingSource.Breakdown]
        BODY_ASSET: _ClassVar[FacebookMarketingSource.Breakdown]
        CALL_TO_ACTION_ASSET: _ClassVar[FacebookMarketingSource.Breakdown]
        COUNTRY: _ClassVar[FacebookMarketingSource.Breakdown]
        DESCRIPTION_ASSET: _ClassVar[FacebookMarketingSource.Breakdown]
        DEVICE_PLATFORM: _ClassVar[FacebookMarketingSource.Breakdown]
        DMA: _ClassVar[FacebookMarketingSource.Breakdown]
        FREQUENCY_VALUE: _ClassVar[FacebookMarketingSource.Breakdown]
        GENDER: _ClassVar[FacebookMarketingSource.Breakdown]
        HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE: _ClassVar[FacebookMarketingSource.Breakdown]
        HOURLY_STATS_AGGREGATED_BY_AUDIENCE_TIME_ZONE: _ClassVar[FacebookMarketingSource.Breakdown]
        IMAGE_ASSET: _ClassVar[FacebookMarketingSource.Breakdown]
        IMPRESSION_DEVICE: _ClassVar[FacebookMarketingSource.Breakdown]
        LINK_URL_ASSET: _ClassVar[FacebookMarketingSource.Breakdown]
        PLACE_PAGE_ID: _ClassVar[FacebookMarketingSource.Breakdown]
        PLATFORM_POSITION: _ClassVar[FacebookMarketingSource.Breakdown]
        PRODUCT_ID: _ClassVar[FacebookMarketingSource.Breakdown]
        PUBLISHER_PLATFORM: _ClassVar[FacebookMarketingSource.Breakdown]
        REGION: _ClassVar[FacebookMarketingSource.Breakdown]
        SKAN_CONVERSION_ID: _ClassVar[FacebookMarketingSource.Breakdown]
        TITLE_ASSET: _ClassVar[FacebookMarketingSource.Breakdown]
        VIDEO_ASSE: _ClassVar[FacebookMarketingSource.Breakdown]
    BREAKDOWN_UNSPECIFIED: FacebookMarketingSource.Breakdown
    AD_FORMAT_ASSET: FacebookMarketingSource.Breakdown
    AGE: FacebookMarketingSource.Breakdown
    APP_ID: FacebookMarketingSource.Breakdown
    BODY_ASSET: FacebookMarketingSource.Breakdown
    CALL_TO_ACTION_ASSET: FacebookMarketingSource.Breakdown
    COUNTRY: FacebookMarketingSource.Breakdown
    DESCRIPTION_ASSET: FacebookMarketingSource.Breakdown
    DEVICE_PLATFORM: FacebookMarketingSource.Breakdown
    DMA: FacebookMarketingSource.Breakdown
    FREQUENCY_VALUE: FacebookMarketingSource.Breakdown
    GENDER: FacebookMarketingSource.Breakdown
    HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE: FacebookMarketingSource.Breakdown
    HOURLY_STATS_AGGREGATED_BY_AUDIENCE_TIME_ZONE: FacebookMarketingSource.Breakdown
    IMAGE_ASSET: FacebookMarketingSource.Breakdown
    IMPRESSION_DEVICE: FacebookMarketingSource.Breakdown
    LINK_URL_ASSET: FacebookMarketingSource.Breakdown
    PLACE_PAGE_ID: FacebookMarketingSource.Breakdown
    PLATFORM_POSITION: FacebookMarketingSource.Breakdown
    PRODUCT_ID: FacebookMarketingSource.Breakdown
    PUBLISHER_PLATFORM: FacebookMarketingSource.Breakdown
    REGION: FacebookMarketingSource.Breakdown
    SKAN_CONVERSION_ID: FacebookMarketingSource.Breakdown
    TITLE_ASSET: FacebookMarketingSource.Breakdown
    VIDEO_ASSE: FacebookMarketingSource.Breakdown
    class ActionBreakdown(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        ACTION_BREAKDOWN_UNSPECIFIED: _ClassVar[FacebookMarketingSource.ActionBreakdown]
        ACTION_CANVAS_COMPONENT_NAME: _ClassVar[FacebookMarketingSource.ActionBreakdown]
        ACTION_CAROUSEL_CARD_ID: _ClassVar[FacebookMarketingSource.ActionBreakdown]
        ACTION_CAROUSEL_CARD_NAME: _ClassVar[FacebookMarketingSource.ActionBreakdown]
        ACTION_DESTINATION: _ClassVar[FacebookMarketingSource.ActionBreakdown]
        ACTION_DEVICE: _ClassVar[FacebookMarketingSource.ActionBreakdown]
        ACTION_REACTION: _ClassVar[FacebookMarketingSource.ActionBreakdown]
        ACTION_TARGET_ID: _ClassVar[FacebookMarketingSource.ActionBreakdown]
        ACTION_TYPE: _ClassVar[FacebookMarketingSource.ActionBreakdown]
        ACTION_VIDEO_SOUND: _ClassVar[FacebookMarketingSource.ActionBreakdown]
        ACTION_VIDEO_TYPE: _ClassVar[FacebookMarketingSource.ActionBreakdown]
    ACTION_BREAKDOWN_UNSPECIFIED: FacebookMarketingSource.ActionBreakdown
    ACTION_CANVAS_COMPONENT_NAME: FacebookMarketingSource.ActionBreakdown
    ACTION_CAROUSEL_CARD_ID: FacebookMarketingSource.ActionBreakdown
    ACTION_CAROUSEL_CARD_NAME: FacebookMarketingSource.ActionBreakdown
    ACTION_DESTINATION: FacebookMarketingSource.ActionBreakdown
    ACTION_DEVICE: FacebookMarketingSource.ActionBreakdown
    ACTION_REACTION: FacebookMarketingSource.ActionBreakdown
    ACTION_TARGET_ID: FacebookMarketingSource.ActionBreakdown
    ACTION_TYPE: FacebookMarketingSource.ActionBreakdown
    ACTION_VIDEO_SOUND: FacebookMarketingSource.ActionBreakdown
    ACTION_VIDEO_TYPE: FacebookMarketingSource.ActionBreakdown
    class InsightConfig(_message.Message):
        __slots__ = ("name", "fields", "breakdowns", "action_breakdowns")
        NAME_FIELD_NUMBER: _ClassVar[int]
        FIELDS_FIELD_NUMBER: _ClassVar[int]
        BREAKDOWNS_FIELD_NUMBER: _ClassVar[int]
        ACTION_BREAKDOWNS_FIELD_NUMBER: _ClassVar[int]
        name: str
        fields: _containers.RepeatedScalarFieldContainer[FacebookMarketingSource.Field]
        breakdowns: _containers.RepeatedScalarFieldContainer[FacebookMarketingSource.Breakdown]
        action_breakdowns: _containers.RepeatedScalarFieldContainer[FacebookMarketingSource.ActionBreakdown]
        def __init__(self, name: _Optional[str] = ..., fields: _Optional[_Iterable[_Union[FacebookMarketingSource.Field, str]]] = ..., breakdowns: _Optional[_Iterable[_Union[FacebookMarketingSource.Breakdown, str]]] = ..., action_breakdowns: _Optional[_Iterable[_Union[FacebookMarketingSource.ActionBreakdown, str]]] = ...) -> None: ...
    START_DATE_FIELD_NUMBER: _ClassVar[int]
    END_DATE_FIELD_NUMBER: _ClassVar[int]
    ACCOUNT_ID_FIELD_NUMBER: _ClassVar[int]
    ACCESS_TOKEN_FIELD_NUMBER: _ClassVar[int]
    INCLUDE_DELETED_FIELD_NUMBER: _ClassVar[int]
    FETCH_THUMBNAIL_IMAGES_FIELD_NUMBER: _ClassVar[int]
    CUSTOM_INSIGHTS_FIELD_NUMBER: _ClassVar[int]
    start_date: str
    end_date: str
    account_id: str
    access_token: str
    include_deleted: bool
    fetch_thumbnail_images: bool
    custom_insights: _containers.RepeatedCompositeFieldContainer[FacebookMarketingSource.InsightConfig]
    def __init__(self, start_date: _Optional[str] = ..., end_date: _Optional[str] = ..., account_id: _Optional[str] = ..., access_token: _Optional[str] = ..., include_deleted: bool = ..., fetch_thumbnail_images: bool = ..., custom_insights: _Optional[_Iterable[_Union[FacebookMarketingSource.InsightConfig, _Mapping]]] = ...) -> None: ...
