# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from doublecloud.access.v1 import access_pb2 as doublecloud_dot_access_dot_v1_dot_access__pb2
from doublecloud.organizationmanager.v1 import group_pb2 as doublecloud_dot_organizationmanager_dot_v1_dot_group__pb2
from doublecloud.organizationmanager.v1 import group_service_pb2 as doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2
from doublecloud.v1 import operation_pb2 as doublecloud_dot_v1_dot_operation__pb2


class GroupServiceStub(object):
    """A set of methods for managing groups.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/Get',
                request_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.GetGroupRequest.SerializeToString,
                response_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__pb2.Group.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/List',
                request_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupsRequest.SerializeToString,
                response_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupsResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/Create',
                request_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/Update',
                request_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.UpdateGroupRequest.SerializeToString,
                response_deserializer=doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/Delete',
                request_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.DeleteGroupRequest.SerializeToString,
                response_deserializer=doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.ListOperations = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/ListOperations',
                request_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupOperationsRequest.SerializeToString,
                response_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupOperationsResponse.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/ListMembers',
                request_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupMembersRequest.SerializeToString,
                response_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupMembersResponse.FromString,
                _registered_method=True)
        self.UpdateMembers = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/UpdateMembers',
                request_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.UpdateGroupMembersRequest.SerializeToString,
                response_deserializer=doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.ListAccessBindings = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/ListAccessBindings',
                request_serializer=doublecloud_dot_access_dot_v1_dot_access__pb2.ListAccessBindingsRequest.SerializeToString,
                response_deserializer=doublecloud_dot_access_dot_v1_dot_access__pb2.ListAccessBindingsResponse.FromString,
                _registered_method=True)
        self.SetAccessBindings = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/SetAccessBindings',
                request_serializer=doublecloud_dot_access_dot_v1_dot_access__pb2.SetAccessBindingsRequest.SerializeToString,
                response_deserializer=doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.UpdateAccessBindings = channel.unary_unary(
                '/doublecloud.organizationmanager.v1.GroupService/UpdateAccessBindings',
                request_serializer=doublecloud_dot_access_dot_v1_dot_access__pb2.UpdateAccessBindingsRequest.SerializeToString,
                response_deserializer=doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)


class GroupServiceServicer(object):
    """A set of methods for managing groups.
    """

    def Get(self, request, context):
        """Returns the specified Group resource.

        To get the list of available Group resources, make a [List] request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Retrieves the list of group resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Creates a group in the specified organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Updates the specified group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Deletes the specified group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOperations(self, request, context):
        """Lists operations for the specified group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """members

        List group active members.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMembers(self, request, context):
        """Update group members.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccessBindings(self, request, context):
        """access

        Lists access bindings for the specified group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAccessBindings(self, request, context):
        """Sets access bindings for the specified group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccessBindings(self, request, context):
        """Updates access bindings for the specified group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.GetGroupRequest.FromString,
                    response_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__pb2.Group.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupsRequest.FromString,
                    response_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupsResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.CreateGroupRequest.FromString,
                    response_serializer=doublecloud_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.UpdateGroupRequest.FromString,
                    response_serializer=doublecloud_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.DeleteGroupRequest.FromString,
                    response_serializer=doublecloud_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'ListOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOperations,
                    request_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupOperationsRequest.FromString,
                    response_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupOperationsResponse.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupMembersRequest.FromString,
                    response_serializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupMembersResponse.SerializeToString,
            ),
            'UpdateMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMembers,
                    request_deserializer=doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.UpdateGroupMembersRequest.FromString,
                    response_serializer=doublecloud_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'ListAccessBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccessBindings,
                    request_deserializer=doublecloud_dot_access_dot_v1_dot_access__pb2.ListAccessBindingsRequest.FromString,
                    response_serializer=doublecloud_dot_access_dot_v1_dot_access__pb2.ListAccessBindingsResponse.SerializeToString,
            ),
            'SetAccessBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccessBindings,
                    request_deserializer=doublecloud_dot_access_dot_v1_dot_access__pb2.SetAccessBindingsRequest.FromString,
                    response_serializer=doublecloud_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'UpdateAccessBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccessBindings,
                    request_deserializer=doublecloud_dot_access_dot_v1_dot_access__pb2.UpdateAccessBindingsRequest.FromString,
                    response_serializer=doublecloud_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doublecloud.organizationmanager.v1.GroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('doublecloud.organizationmanager.v1.GroupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupService(object):
    """A set of methods for managing groups.
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/Get',
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.GetGroupRequest.SerializeToString,
            doublecloud_dot_organizationmanager_dot_v1_dot_group__pb2.Group.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/List',
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupsRequest.SerializeToString,
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/Create',
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.CreateGroupRequest.SerializeToString,
            doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/Update',
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.UpdateGroupRequest.SerializeToString,
            doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/Delete',
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.DeleteGroupRequest.SerializeToString,
            doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/ListOperations',
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupOperationsRequest.SerializeToString,
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/ListMembers',
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupMembersRequest.SerializeToString,
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.ListGroupMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/UpdateMembers',
            doublecloud_dot_organizationmanager_dot_v1_dot_group__service__pb2.UpdateGroupMembersRequest.SerializeToString,
            doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccessBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/ListAccessBindings',
            doublecloud_dot_access_dot_v1_dot_access__pb2.ListAccessBindingsRequest.SerializeToString,
            doublecloud_dot_access_dot_v1_dot_access__pb2.ListAccessBindingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAccessBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/SetAccessBindings',
            doublecloud_dot_access_dot_v1_dot_access__pb2.SetAccessBindingsRequest.SerializeToString,
            doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccessBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublecloud.organizationmanager.v1.GroupService/UpdateAccessBindings',
            doublecloud_dot_access_dot_v1_dot_access__pb2.UpdateAccessBindingsRequest.SerializeToString,
            doublecloud_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
