name: Generate code from protobuf specifications

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  genproto:
    runs-on: ubuntu-latest
    # disallows two or more release jobs to run in parallel
    concurrency: genproto

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: '**/requirements-dev.txt'

    - name: Generate code from proto
      run: |
        make venv
        make generate
        
        git config --global user.name 'Double.Cloud Bot'
        git config --global user.email 'bot@double.cloud'
        git add api doublecloud
        git commit -m 'build: regenerate proto' || echo "No changes in .proto files found"
        git push
